### ISSUE TITLE
Can we parametrize the pipeline DAG to generic Mario flow

### ISSUE THREAD

**Issue by mrharpo** [WGBH-MLA/mario#5]
Investigate the possibility of using logic in flow steps.

**Comment by mrharpo** [comment]
# TLDR
No. But... there are some workarounds.

See 👇

**Comment by mrharpo** [comment]
# skip
We can "skip" a step by wrapping the function and checking for a condition

```py
from functools import wraps

from metaflow import FlowSpec, Parameter, step


class skip:  # noqa N801
    def __init__(self, check='', next=''):
        self.check = check
        self.next = next

    def __call__(self, f):
        @wraps(f)
        def func(s):
            if getattr(s, self.check):
                return f(s)

            s.next(getattr(s, self.next))
            return None

        return func


class SkipFlow(FlowSpec):
    condition = Parameter('condition', default=0)

    @step
    def start(self):
        print('Should skip:', self.condition)
        self.next(self.middle)

    @skip(check='condition', next='end')
    @step
    def middle(self):
        print('Running the middle step - not skipping')
        self.next(self.end)

    @step
    def end(self):
        pass


if __name__ == '__main__':
    SkipFlow()
```
(From a metaflow slack thread)

### Cons
- The step still runs
  - This does not really "skip" the step, but bypasses the business logic. In a k8s environment, the step still has to load an run, so this does not save us much
  - We can only run these steps in a predefined order

**Comment by mrharpo** [comment]
# pipeline: []
We can pass a `pipeline = [...]` parameter to a flow, but we can't `foreach` over it because the steps would run in parallel, and we need them to run in series.
```py
from metaflow import FlowSpec, Parameter, step


class Pipeline(FlowSpec):
    guid = Parameter('guid', help='GUID of the transcript to process')
    pipeline = Parameter('pipeline', help='Pipeline to run', multiple=True)

    @step
    def start(self):
        print(f'Starting {self.guid} through {self.pipeline}')
        self.next(self.apps)

    @step
    def apps(self):
        for app in self.pipeline:
            print('App', app)
        self.next(self.end)

    @step
    def end(self):
        print('Flow completed.')


if __name__ == '__main__':
    Pipeline()

```


### Pros
- Simple
- Can pass an arbitrary list of html links to apps

### Cons
- Combins the runs of all apps in the pipeline
  - Ideally, they would each be a metaflow step with an mmif artifact

**Comment by mrharpo** [comment]
# Trigger
We might be able to use [metaflow's @trigger_on_finish](https://docs.metaflow.org/api/flow-decorators/trigger_on_finish) decorator, but it is a `FlowSpec` decorator, so we can't pass parameters to it.

But we can still use it to define pipelines that call a sequence of existing Flows:

```py
from metaflow import FlowSpec, Parameter, step, trigger_on_finish


@trigger_on_finish(flows=['AppBarsdetection'], options={'parameters': {'guid': 'guid'}})
class TriggerPipeline(FlowSpec):
    guid = Parameter('guid', help='GUID of the transcript to process')

    @step
    def start(self):
        print(f'Prepping {self.guid} for AppBarsdetection pipeline')
        self.next(self.end)

    @step
    def end(self):
        print('Ready to begin pipeline!')


if __name__ == '__main__':
    TriggerPipeline()
```

### Pros
- Reusable apps
- Good separation of concerns

### Cons
- Still have to create a Flow per pipeline 
  - metaflow + mario
  - deploy to production

**Comment by afred** [comment]
I'm afraid [the trigger works the other way around though](https://docs.metaflow.org/production/event-triggering/flow-events).
```
class FirstFlow(FlowSpec):
  ...

@trigger_on_finish(flow='FirstFlow')
class SecondFlow(FlowSpec):
  ...
```

**Comment by afred** [comment]
We can still use `@trigger_on_finish` to provide a layer of abstraction between the flow that is triggered when a Chowda user publishes the triggering Argo Event, and other Flows that get run:
```
@trigger(event='app-barsdetection')
class BarsDetectionPipeline(FlowSpec):
   ...

@trigger_on_finish(flow='BarsDetectionPipeline')
class BarsDetectionFlow(FlowSpec):
  ...
```

**Comment by mrharpo** [comment]
It also means we would need 1 flow per app per pipeline, which doesn't scale.
